# Overrides production : docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# Scalabilité : docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --scale api=3
name: footcoach

services:
  postgres:
    restart: unless-stopped
    ports: []

  api:
    build:
      target: prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes: []

  web:
    build:
      target: prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes: []
